"""add time_currency to ExchangeHistory

Revision ID: 31232f655872
Revises: e61dffcc7d92
Create Date: 2025-05-03 11:55:07.901048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31232f655872'
down_revision: Union[str, None] = 'e61dffcc7d92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exchangehistory', sa.Column('time_currency', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exchangehistory', 'time_currency')
    # ### end Alembic commands ###
